version: '3'

services:

  mongodb:
    image: bitnami/mongodb:5.0.4
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    environment:
      - MONGODB_DATABASE=restdb
      - MONGODB_USERNAME=test
      - MONGODB_PASSWORD=test
      - MONGODB_ROOT_PASSWORD=other
    networks:
      - backend
  
  app:
    build: .
    depends_on: 
      - mongodb
    networks:
      - frontend
      - backend

  nginx:
    image: nginx:1.20-alpine
    ports: 
      - "80:80"
    volumes:
      - ./nginx/static/:/usr/share/nginx/html/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - app
    networks:
      - app
      - frontend

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  app:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge