version: '3'

services:
  jenkins:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
    networks:
      - star

volumes:
  jenkins_home:

networks:
  star:
    driver: bridge